baseurl = "https://ecmascript2015.herokuapp.com/"
languageCode = "en-us"
title = "ES6 Features"
theme = "blackburn"
canonifyurls = true

[params]
  # Shown in the home page
  subtitle = "Jquery"
  brand = "Jquery Features"
  custom_css = ["css/custom_style.css"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = ""
    weight = 0
    identifier = "home"
    url = "/"

